# [package]
# order = "Alphabetic"

# [package]
# order = "Alphabetic"

# [features]
# order = ["default"]

[features]
order = "Alphabetic"

# [badges]
# order = "Alphabetic"

# [badges."*"]
# order = ["branch", "repository"]
