[package]
name = "serde"
version = "1.0.110" # remember to update html_root_url and serde_derive dependency
authors = ["David Tolnay <dtolnay@gmail.com>", "Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
description = "A generic serialization/deserialization framework"
documentation = "https://docs.serde.rs/serde/"
readme = "crates-io.md"
homepage = "https://serde.rs"
repository = "https://github.com/serde-rs/serde"
license = "MIT OR Apache-2.0"
keywords = ["no_std", "serde", "serialization"]
categories = ["encoding"]
build = "build.rs"
include = ["Cargo.toml", "LICENSE-APACHE", "LICENSE-MIT", "README.md", "build.rs", "crates-io.md", "src/**/*.rs"]
metadata = { playground = { features = ["rc", "derive"] }, docs = { rs = { targets = ["x86_64-unknown-linux-gnu"] } } }

[dependencies]
serde_derive = { version = "=1.0.110", path = "../serde_derive", optional = true }

[dev-dependencies]
serde_derive = { version = "1.0", path = "../serde_derive" }

# FEATURES #################################################################
[features]
default = ["std"]
# Provide impls for types in the Rust core allocation and collections library
# including String, Box<T>, Vec<T>, and Cow<T>. This is a subset of std but may
# be enabled without depending on all of std.
alloc = []
# Provide derive(Serialize, Deserialize) macros.
derive = ["serde_derive"]
# Opt into impls for Rc<T> and Arc<T>. Serializing and deserializing these types
# does not preserve identity and may result in multiple copies of the same data.
# Be sure that this is what you want before enabling this feature.
rc = []
# Provide impls for common standard library types like Vec<T> and HashMap<K, V>.
# Requires a dependency on the Rust standard library.
std = []
# Provide impls for types that require unstable functionality. For tracking and
# discussion of unstable functionality please refer to this issue:
#
#    https://github.com/serde-rs/serde/issues/812
unstable = []