[package]
name = "rand"
version = "0.7.4"
authors = ["The Rand Project Developers", "The Rust Project Developers"]
edition = "2018"
description = """
Random number generators and other randomness functionality.
"""
documentation = "https://rust-random.github.io/rand/"
readme = "README.md"
homepage = "https://crates.io/crates/rand"
repository = "https://github.com/rust-random/rand"
license = "MIT OR Apache-2.0"
keywords = ["random", "rng"]
categories = ["algorithms", "no-std"]
include = ["CHANGELOG.md", "COPYRIGHT", "LICENSE-*", "README.md", "src/"]
autobenches = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
log = { version = "0.4.4", optional = true }
packed_simd = { version = "0.3", optional = true, features = ["into_bits"] }
rand_core = { version = "0.5.1", path = "rand_core" }
rand_pcg = { version = "0.2.1", path = "rand_pcg", optional = true }
serde = { version = "1.0.103", optional = true, features = ["derive"] }

[dev-dependencies]
# Only to test serde1
bincode = "1.2.1"
# Only for benches:
rand_hc = { version = "0.2", path = "rand_hc" }
rand_pcg = { version = "0.2", path = "rand_pcg" }

# Emscripten does not support 128-bit integers, which are used by ChaCha code.
# We work around this by using a different RNG.
[target.'cfg(not(target_os = "emscripten"))'.dependencies]
rand_chacha = { path = "rand_chacha", version = "0.2.3", default-features = false, optional = true }

[target.'cfg(target_os = "emscripten")'.dependencies]
rand_hc = { path = "rand_hc", version = "0.2.1", optional = true }

[target.'cfg(unix)'.dependencies]
# Used for fork protection (reseeding.rs)
libc = { version = "0.2.22", optional = true, default-features = false }

[badges]
appveyor = { repository = "rust-random/rand" }
travis-ci = { repository = "rust-random/rand" }

[features]
# Meta-features:
default = ["std", "std_rng"]
# Option: "alloc" enables support for Vec and Box when not using "std"
alloc = ["rand_core/alloc"]
# Option: use getrandom package for seeding
getrandom = ["rand_core/getrandom"]
nightly = ["simd_support"] # enables all features requiring nightly rust
serde1 = ["serde"]
# Option (requires nightly): experimental SIMD support
simd_support = ["packed_simd"]
# Option: enable SmallRng
small_rng = ["rand_pcg"]
# Option (enabled by default): without "std" rand uses libcore; this option
# enables functionality expected to be available on a standard platform.
std = ["alloc", "getrandom", "libc", "rand_chacha/std", "rand_core/std"]
# Option (enabled by default): enable StdRng
std_rng = ["rand_chacha", "rand_hc"]

[workspace]
members = ["rand_chacha", "rand_core", "rand_distr", "rand_hc", "rand_pcg"]