order = [
    "package",
    "lib",
    "bin",
    "example",
    "test",
    "bench",
    "dependencies",
    "dev-dependencies",
    "build-dependencies",
    "target",
    "badges",
    "features",
    "replace",
    "patch",
    "profile",
    "workspace",
]

[package]
order = [
    "name",
    "version",
    "authors",
    "edition",
    "description",
    "documentation",
    "readme",
    "homepage",
    "repository",
    "license",
    "license-file",
    "keywords",
    "categories",
    "workspace",
    "build",
    "links",
    "exclude",
    "include",
    "publish",
    "metadata",
    "default-run",
    "autobins",
    "autoexamples",
    "autotests",
    "autobenches",
]
inline = 1

[package.authors]
order = "Alphabetic"

[package.keywords]
order = "Alphabetic"

[package.categories]
order = "Alphabetic"

[package.exclude]
order = "Alphabetic"

[package.include]
order = "Alphabetic"

[package.metadata]
order = "Alphabetic"
inline = "None"

[lib]
order = [
    "name",
    "path",
    "test",
    "doctest",
    "bench",
    "doc",
    "plugin",
    "proc-macro",
    "harness",
    "edition",
    "crate-type",
    "required-features",
]

[lib.crate-type]
order = "Alphabetic"

[bin]
order = [
    "name",
    "path",
    "test",
    "doctest",
    "bench",
    "doc",
    "plugin",
    "proc-macro",
    "harness",
    "edition",
    "crate-type",
    "required-features",
]

[bin.required-features]
order = "Alphabetic"

[example]
order = [
    "name",
    "path",
    "test",
    "doctest",
    "bench",
    "doc",
    "plugin",
    "proc-macro",
    "harness",
    "edition",
    "crate-type",
    "required-features",
]

[example.required-features]
order = "Alphabetic"

[test]
order = [
    "name",
    "path",
    "test",
    "doctest",
    "bench",
    "doc",
    "plugin",
    "proc-macro",
    "harness",
    "edition",
    "crate-type",
    "required-features",
]

[test.required-features]
order = "Alphabetic"

[bench]
order = [
    "name",
    "path",
    "test",
    "doctest",
    "bench",
    "doc",
    "plugin",
    "proc-macro",
    "harness",
    "edition",
    "crate-type",
    "required-features",
]

[bench.crate-type]
order = "Alphabetic"

[bench.required-features]
order = "Alphabetic"

[dependencies]
order = "Alphabetic"
inline = 1

[dependencies."*"]
order = [
    "version",
    "git",
    "branch",
    "rev",
    "tag",
    "path",
    "registry",
    "package",
    "optional",
    "default-features",
    "features",
]

[dev-dependencies]
order = "Alphabetic"
inline = 1

[dev-dependencies."*"]
order = [
    "version",
    "git",
    "branch",
    "rev",
    "tag",
    "path",
    "registry",
    "package",
    "optional",
    "default-features",
    "features",
]

[build-dependencies]
order = "Alphabetic"
inline = 1

[build-dependencies."*"]
order = [
    "version",
    "git",
    "branch",
    "rev",
    "tag",
    "path",
    "registry",
    "package",
    "optional",
    "default-features",
    "features",
]

[targets]
order = "Alphabetic"

[targets.dependencies]
order = "Alphabetic"
inline = 1

[targets.dependencies."*"]
order = [
    "version",
    "git",
    "branch",
    "rev",
    "tag",
    "path",
    "registry",
    "package",
    "optional",
    "default-features",
    "features",
]

[targets.dev_dependencies]
order = "Alphabetic"
inline = 1

[targets.dev_dependencies."*"]
order = [
    "version",
    "git",
    "branch",
    "rev",
    "tag",
    "path",
    "registry",
    "package",
    "optional",
    "default-features",
    "features",
]

[targets.build_dependencies]
order = "Alphabetic"
inline = 1

[targets.build_dependencies."*"]
order = [
    "version",
    "git",
    "branch",
    "rev",
    "tag",
    "path",
    "registry",
    "package",
    "optional",
    "default-features",
    "features",
]

[targets."*"]
order = [
    "dependencies",
    "dev-dependencies",
    "build-dependencies",
]

[badges]
order = [
    "appveyor",
    "circle-ci",
    "cirrus-ci",
    "gitlab",
    "azure-devops",
    "travis-ci",
    "bitbucket-pipelines",
    "codecov",
    "coveralls",
    "is-it-maintained-issue-resolution",
    "is-it-maintained-open-issues",
    "maintenance",
]
inline = 1

[badges."*"]
order = [
    "repository",
    "branch",
    "service",
    "project",
    "pipeline",
    "build",
]

[features]
order = ["default"]

[features."*"]
order = "Alphabetic"

[patch]
order = "Alphabetic"
inline = 2

[replace]
order = "Alphabetic"

[profiles]
order = [
    "dev",
    "release",
    "test",
    "bench",
]
inline = 1

[profiles."*"]
order = [
    "opt-level",
    "debug",
    "debug-assertions",
    "overflow-checks",
    "lto",
    "panic",
    "incremental",
    "codegen-units",
    "rpath",
]

[workspace]
order = [
    "members",
    "default-members",
    "exclude",
]

[workspace.members]
order = "Alphabetic"

[workspace.default_members]
order = "Alphabetic"

[workspace.exclude]
order = "Alphabetic"
